Repository React-Linkshop-6team/react-linkshop, pull requests merged in 2025-05, with the labels that each got.

#124 [Fix-121] 메인화면 검색 기능 수정
  src/api/api.js
  src/assets/scss/ShopCard/ShopCard.scss
  src/assets/scss/ShopList/ShopList.scss
  src/components/Header.jsx
  src/components/ShopList/ShopList.jsx
  src/pages/Home.jsx
Labels: 🐞 Bug

#129 [fix - 123] 내가 생성한 상점이면 메인페이지에서도 수정/삭제가능
  src/assets/scss/AboutShop/AboutShop.scss
  src/assets/scss/DetailPageItemList/DetailPageItemList.scss
  src/assets/scss/EditDeleteModal/EditDeleteModal.scss
  src/assets/scss/ProFileDetail/ProFileDetail.scss
  src/assets/scss/Styles.scss
  src/components/AboutShop/AboutShop.jsx
  src/components/CheckDeletePageModal/CheckDeletePageModal.jsx
  src/components/DetailPageItemList/DetailPageItemList.jsx
  src/components/EditDeleteModal/EditDeleteModal.jsx
  src/components/InputPasswordModal/InputPasswordModal.jsx
  src/components/ModalStateControl/ModalStateControl.jsx
  src/pages/MyStore.jsx
  src/pages/ProfileDetail.jsx
Labels: 🐞 Bug, 📦 Chore

#130 [fix - 113] 생성하기 기능에러 수정
  src/components/common/Create/CreateMyshop.jsx
  src/components/common/Create/CreateRepItemImageUploader.jsx
  src/pages/Create.jsx
Labels: 🐞 Bug

#133 [Feat-122] 404 error page 추가
  src/App.jsx
  src/assets/scss/NotFound/NotFound.scss
  src/assets/scss/Styles.scss
  src/pages/NotFound.jsx
Labels: ✨ Feat
