Repository React-Linkshop-6team/react-linkshop, pull requests merged in 2025-04, with the labels that each got.

#10 test: merge test hyun
  src/App.jsx
Labels: ✨ Feat

#15 [Feat] 화면 페이지 분기 처리 #14
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .vscode/settings.json
  eslint.config.js
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/common/Button.jsx
  src/index.css
  src/pages/Create.jsx
  src/pages/Edit.jsx
  src/pages/Home.jsx
  src/pages/ProfileDetail.jsx
Labels: ✨ Feat

#18 Feat 16, 17 이슈 사항 적용
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/logo.png
  src/assets/scss/Button.scss
  src/assets/scss/Header.scss
  src/assets/scss/Setting.scss
  src/assets/scss/Styles.scss
  src/components/Header.jsx
  src/components/common/Button.jsx
Labels: ✨ Feat

#19 docs: README.md 파일 작성
  README.md
Labels: 📄 Docs

#24 feat #22 : 상세페이지 헤더부분 구현
  src/assets/images/detail-img.png
  src/assets/images/empty-heart.png
  src/assets/images/filter-icon.png
  src/assets/images/go-to-back.png
  src/assets/images/url-copy-icon.png
  src/assets/scss/ProFileDetail.scss
  src/assets/scss/Styles.scss
  src/components/Header.jsx
  src/pages/ProfileDetail.jsx
Labels: ✨ Feat

#25 [Feat] 메인화면 상품 카드 보이도록 API 연결
  eslint.config.js
  package-lock.json
  package.json
  src/api/api.js
  src/assets/scss/ShopCard/ShopCard.scss
  src/assets/scss/ShopLike/ShopLike.scss
  src/assets/scss/ShopList/ShopList.scss
  src/assets/scss/ShopProfile/ShopProfile.scss
  src/assets/scss/Styles.scss
  src/components/ShopCard/ShopCard.jsx
  src/components/ShopLike/ShopLike.jsx
  src/components/ShopList/ShopList.jsx
  src/components/ShopProfile/ShopProfile.jsx
  src/components/ThumbnailList/ThumbnailList.jsx
  src/mock/mockData.js
  src/pages/Home.jsx
Labels: ✨ Feat

#26 [docs] README.md 파일 최종
  README.md
Labels: 📄 Docs

#32 [Feat] 샵 검색 기능, 상세 필터 기능 구현
  src/assets/images/no-search.png
  src/assets/images/search-icon.png
  src/assets/scss/FilterModal/FilterModal.scss
  src/assets/scss/NoResult/NoResult.scss
  src/assets/scss/SearchBar/SearchBar.scss
  src/assets/scss/ShopList/ShopList.scss
  src/assets/scss/Styles.scss
  src/components/FilterModal/FilterModal.jsx
  src/components/Header.jsx
  src/components/NoResult/NoResult.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/ShopList/ShopList.jsx
  src/mock/mockData.js
Labels: ✨ Feat

#35 feat #28 : 공유하기 버튼, 더보기 버튼 기능추가
  src/assets/scss/EditDeleteModal.scss
  src/assets/scss/ProFileDetail.scss
  src/assets/scss/Styles.scss
  src/components/EditDeleteModal.jsx
  src/components/InputPasswordModal.jsx
  src/components/ModalStateControl.jsx
  src/pages/ProfileDetail.jsx
Labels: ✨ Feat

#40 feat #39 : 수정하기 모달에 css적용하기
  src/assets/scss/EditDeleteModal.scss
  src/assets/scss/ProFileDetail.scss
  src/components/InputPasswordModal.jsx
  src/pages/ProfileDetail.jsx
Labels: ✨ Feat, 📦 Chore

#41 [feat-30] 생성하기 페이지 구현
  src/assets/scss/Create/Create.scss
  src/assets/scss/Create/RepItem.scss
  src/assets/scss/Styles.scss
  src/components/common/RepItem.jsx
Labels: ✨ Feat

#44 [Feat-#38] 메인화면 반응형 디자인 구현 + 상수 폴더 생성
  .gitignore
  src/App.jsx
  src/api/api.js
  src/assets/images/polygon-filter.png
  src/assets/scss/Button.scss
  src/assets/scss/FilterModal/FilterModal.scss
  src/assets/scss/Header.scss
  src/assets/scss/NoResult/NoResult.scss
  src/assets/scss/SearchBar/SearchBar.scss
  src/assets/scss/Setting.scss
  src/assets/scss/ShopCard/ShopCard.scss
  src/assets/scss/ShopLike/ShopLike.scss
  src/assets/scss/ShopList/ShopList.scss
  src/assets/scss/ShopProfile/ShopProfile.scss
  src/assets/scss/ThumbnailList/ThumbnailList.scss
  src/components/FilterModal/FilterModal.jsx
  src/components/ShopCard/ShopCard.jsx
  src/components/ShopList/ShopList.jsx
  src/components/ShopProfile/ShopProfile.jsx
  src/components/common/ShopLike.jsx
  src/constants/color.js
  src/constants/filterOptions.js
  src/pages/Home.jsx
Labels: ✨ Feat

#47 Feat #42 : 좋아요버튼 상세페이지 적용/ API GET 요청
  src/api/api.js
  src/components/ShopProfile/ShopProfile.jsx
  src/pages/ProfileDetail.jsx
Labels: ✨ Feat

#45 [feat] 생성하기 페이지 내쇼핑몰 구현
  src/App.jsx
  src/assets/images/eyes.png
  src/assets/scss/Edit.scss
  src/assets/scss/Myshop.scss
  src/assets/scss/ShopImg.scss
  src/assets/scss/ShopInfo.scss
  src/assets/scss/Styles.scss
  src/components/Myshop.jsx
  src/components/common/ShopImg/ShopImg.jsx
  src/components/common/ShopInfo/ShopInfo.jsx
Labels: ✨ Feat

#51 [Feat #48] : 상세페이지 api 연결하기
  src/api/api.js
  src/assets/scss/DetailPageItemList.scss
  src/assets/scss/ShopCard/ShopCard.scss
  src/assets/scss/Styles.scss
  src/components/DetailPageItemList.jsx
  src/components/Header.jsx
  src/components/InputPasswordModal.jsx
  src/components/ModalStateControl.jsx
  src/components/ShopProfile/ShopProfile.jsx
  src/pages/ProfileDetail.jsx
Labels: ✨ Feat

#52 [Feat] 내쇼핑몰 유저ID, PW 부분 분리 및 API처리
  src/App.jsx
  src/api/api.js
  src/assets/scss/Edit/EditMyshop.scss
  src/assets/scss/Edit/EditRepItem.scss
  src/assets/scss/Myshop.scss
  src/assets/scss/ShopImg.scss
  src/assets/scss/Styles.scss
  src/components/common/Edit/EditMyshop.jsx
  src/components/common/Edit/EditRepItem.jsx
  src/components/common/Myshop.jsx
  src/pages/Edit.jsx
Labels: ✨ Feat

#66 feat-56-createcomponent/addcss
  .husky/pre-commit
  package-lock.json
  package.json
  src/api/api.js
  src/assets/images/filter-icon.png
  src/assets/images/url-copy-icon.png
  src/assets/scss/AboutShop 2.scss
  src/assets/scss/AboutShop 3.scss
  src/assets/scss/AboutShop 4.scss
  src/assets/scss/AboutShop.scss
  src/assets/scss/DetailPageItemList.scss
  src/assets/scss/EditDeleteModal.scss
  src/assets/scss/ProFileDetail.scss
  src/assets/scss/Styles.scss
  src/components/AboutShop.jsx
  src/components/CheckDeletePageModal.jsx
  src/components/DetailPageItemList.jsx
  src/components/EditDeleteModal.jsx
  src/components/InputPasswordModal.jsx
  src/components/ModalStateControl.jsx
  src/components/ShopProfile/ShopProfile.jsx
  src/pages/ProfileDetail.jsx
Labels: ✨ Feat

#70 [feat 64] 상품이 등록 됐을 때 페이지네이션 구현
  src/components/common/Create/CreateMyshop.jsx
  src/pages/Create.jsx
Labels: ✨ Feat

#69 [feat 58] defalt value 기능 구현
  src/App.jsx
  src/api/api.js
  src/assets/scss/Edit/EditRepItem.scss
  src/components/common/Create/CreateMyshop.jsx
  src/components/common/Create/CreateRepItem.jsx
  src/components/common/Edit/EditRepItem.jsx
  src/pages/Create.jsx
  src/pages/Edit.jsx
Labels: ✨ Feat

#71 [Refactor-68] 메인화면 성능 최적화 및 무한스크롤 에러 해결
  eslint.config.js
  package-lock.json
  package.json
  src/api/api.js
  src/assets/images/linkshop.png
  src/assets/scss/ShopList/ShopList.scss
  src/assets/scss/Spinner/Spinner.scss
  src/assets/scss/Styles.scss
  src/components/ShopCard/ShopCard.jsx
  src/components/ShopList/ShopList.jsx
  src/components/common/Spinner.jsx
  src/constants/filterOptions.js
  src/pages/Home.jsx
Labels: 🐞 Bug, Refactor

#73 [feat-72] 수정하기 API연결
  package-lock.json
  src/api/api.js
  src/assets/scss/Edit.scss
  src/assets/scss/Edit/Edit.scss
  src/assets/scss/Edit/EditMyshop.scss
  src/assets/scss/Edit/EditRepItem.scss
  src/assets/scss/Styles.scss
  src/components/common/Create/CreateRepItem.jsx
  src/components/common/Edit/EditMyshop.jsx
  src/components/common/Edit/EditRepItem.jsx
  src/pages/Create.jsx
  src/pages/Edit.jsx
Labels: ✨ Feat

#74 [Feat - 67] 수정하기/삭제하기 API 기능구현 / SCSS 수정.
  src/api/api.js
  src/assets/scss/AboutShop 2.scss
  src/assets/scss/AboutShop 3.scss
  src/assets/scss/AboutShop 4.scss
  src/assets/scss/EditDeleteModal.scss
  src/assets/scss/ProFileDetail.scss
  src/components/CheckDeletePageModal.jsx
  src/components/EditDeleteModal.jsx
  src/components/InputPasswordModal.jsx
Labels: ✨ Feat

#79 [fix-61] 생성하기 사진 깨짐 메인화면에서 불러올 때 못 불러옴
  package-lock.json
  src/api/api.js
  src/components/DetailPageItemList.jsx
  src/components/InputPasswordModal.jsx
  src/components/ShopProfile/ShopProfile.jsx
  src/components/common/Create/CreateMyshop.jsx
  src/components/common/Create/CreateShopInfo.jsx
  src/pages/Create.jsx
Labels: 🐞 Bug

#85 [Feat-53] Firebase 로그인/회원가입 + 샵 생성/삭제 등 CRUD 로직 연동
  eslint.config.js
  package-lock.json
  package.json
  src/App.jsx
  src/api/api.js
  src/assets/scss/Edit/EditRepItem.scss
  src/assets/scss/Header.scss
  src/assets/scss/Login/Login.scss
  src/assets/scss/Signup/Signup.scss
  src/assets/scss/Styles.scss
  src/components/AboutShop.jsx
  src/components/CheckDeletePageModal.jsx
  src/components/DetailPageItemList.jsx
  src/components/EditDeleteModal.jsx
  src/components/Header.jsx
  src/components/InputPasswordModal.jsx
  src/components/ModalStateControl.jsx
  src/components/common/Create/CreateMyshop.jsx
  src/components/common/Create/CreateRepItem.jsx
  src/components/common/Edit/EditRepItem.jsx
  src/firebase.js
  src/pages/Create.jsx
  src/pages/Edit.jsx
  src/pages/Login.jsx
  src/pages/MyStore.jsx
  src/pages/ProfileDetail.jsx
  src/pages/Signup.jsx
Labels: ✨ Feat

#102 fix: 메인화면에서 userId가 제대로 출력되지 않는 현상 해결
  src/components/ShopCard/ShopCard.jsx
  src/components/ShopProfile/ShopProfile.jsx
Labels: 🐞 Bug

#104 [Fix -103] 상세페이지 비밀번호확인아이콘수정
  src/assets/scss/EditDeleteModal.scss
  src/assets/scss/ProFileDetail.scss
  src/pages/Edit.jsx
Labels: 🐞 Bug

#111 [Feat-109] 로그인/회원가입 password show hide 작업 구현
  src/assets/scss/Login/Login.scss
  src/assets/scss/Signup/Signup.scss
  src/pages/Edit.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: ✨ Feat

#118 [Fix - 116] header 렌더링 / 불필요한 주석,console제거
  src/components/DetailPageItemList.jsx
  src/components/FilterModal/FilterModal.jsx
  src/components/Header.jsx
  src/components/common/Create/CreateMyshop.jsx
  src/components/common/Myshop.jsx
  src/pages/Create.jsx
  src/pages/Login.jsx
  src/pages/ProfileDetail.jsx
  src/pages/Signup.jsx
Labels: 🐞 Bug, 📦 Chore
